movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('movie_recommend/', views.movie_recommend, name='movie_recommend'),
    path('movie_upcoming/', views.movie_upcoming, name='movie_upcoming'),

    path('review_top_movie/', views.review_top_movie, name='review_top_movie'),
    path('review_list/', views.review_list, name='review_list'),
    path('review_list_movie/<int:movie_id>/', views.review_list_movie, name="review_list_movie"),
    path('review/<int:review_id>/', views.review_detail, name="review_detail"),
    path('review_create_withoutmovie/', views.review_create_withoutmovie, name='review_create_withoutmovie'),
    path('review_create/<int:movie_id>/', views.review_create, name='review_create'),
    path('review_update/<int:review_id>/', views.review_update, name="review_update"),
    path('review_delete/<int:review_id>/', views.review_delete, name="review_delete"),

    path('movie_like/<int:movie_id>/', views.movie_like, name='movie_like'),
    path('movie_exclude/<int:movie_id>/', views.movie_exclude, name='movie_exclude'),
    path('movie_later/<int:movie_id>/', views.movie_later, name='movie_later'),

    path('get_movies/<int:pageNum>/<int:key>/<int:genre_key>/', views.get_movies, name='get_movies'),
    path('search_movies/<str:searchInput>/<int:pageNum>/', views.search_movies, name='search_movies'),

    path('get_genres/<int:movie_id>/', views.get_genres, name='get_genres'),
    path('get_reviews/<int:movie_id>/', views.get_reviews, name='get_reviews'),
    path('make_review/<int:movie_id>/', views.make_review, name='make_review'),
    path('get_movie_recommend/<str:weather>/<str:temp>/', views.get_movie_recommend, name='get_movie_recommend'),

]

movies/models.py
from django.db import models
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=50)
    original_title = models.CharField(max_length=50)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=50)
    poster_path = models.CharField(max_length=50)
    backdrop_path = models.CharField(max_length=50)
    genres = models.ManyToManyField(Genre)

    def __str__(self):
        return self.title


class MovieReview(models.Model):
    content = models.CharField(max_length = 50)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    score = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/forms.py
from django import forms
from .models import MovieReview


SCORE_CHOICES = (('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10))
class MovieReviewForm(forms.ModelForm):
    class Meta:
        model = MovieReview
        fields = ['content', 'score']
        widgets = {
            'score': forms.Select(choices=SCORE_CHOICES)
        }


class MovieReviewWithoutMovieForm(forms.ModelForm):
    class Meta:
        model = MovieReview
        fields = ['content', 'movie', 'score']
        widgets = {
            'score': forms.Select(choices=SCORE_CHOICES)
        }

movieday/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaulttags import register
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Q
from django.contrib import messages

from movieday.settings import SECRET_KEY_WEATHER_API_KEY, SECRET_KEY_MOVIE_API_KEY, SECRET_KEY_KOBIS_API_KEY
from .models import Movie, Genre, MovieReview
from .forms import MovieReviewForm, MovieReviewWithoutMovieForm

import random, json

def index(request):
    movie_count = Movie.objects.all().count()
    review_count = MovieReview.objects.all().count()
    context = {
        'movie_count': movie_count,
        'review_count': review_count,
    }
    return render(request, 'movies/index.html', context)

@login_required
def movie_list(request):
    movie_cnt = Movie.objects.exclude(id__in=request.user.exclude_movies.all()).count() // 16
    context = {
        'movie_cnt': movie_cnt
    }
    return render(request, 'movies/movies_list.html', context)

@login_required
def movie_recommend(request):
    user = request.user

    if user.like_movies.exists() or user.like_genres.exists():
        genres_cnt = dict()

        for movie in user.like_movies.all():
            for genre in movie.genres.all():
                genres_cnt[genre.name] = genres_cnt.get(genre.name, 0) + 1

        for genre in user.like_genres.all():
            genres_cnt[genre.name] = genres_cnt.get(genre.name, 0) + 1

        max_genres = []
        if genres_cnt:
            max_cnt = max(genres_cnt.values())
        else:
            max_cnt = 0

        for genre, cnt in genres_cnt.items():
            if cnt == max_cnt:
                max_genres.append(genre)

        while True:
            recommend_genre = random.choice(max_genres)
            reason = 1
            if Genre.objects.get(name=recommend_genre).movie_set.exclude(id__in=user.like_movies.all()).exclude(id__in=user.exclude_movies.all()).exclude(id__in=user.later_movies.all()).order_by('-vote_average', '-release_date'):
                break
            else:
                max_genres.remove(recommend_genre)
                if not max_genres:
                    recommend_genre = random.choice(Genre.objects.exclude(name="TV Movie").exclude(name="History"))
                    reason = 2
                    break
    else:
        recommend_genre = random.choice(Genre.objects.exclude(name="TV Movie").exclude(name="History"))
        reason = 3

    recommend_movies_genre = Genre.objects.get(name=recommend_genre).movie_set.exclude(id__in=user.like_movies.all()).exclude(id__in=user.exclude_movies.all()).exclude(id__in=user.later_movies.all()).order_by('-vote_average', '-release_date')[:18]

    recommend_movies_score = Movie.objects.all().exclude(id__in=user.like_movies.all()).exclude(id__in=user.exclude_movies.all()).exclude(id__in=user.later_movies.all()).order_by('-vote_average', '-release_date')[:18]

    context = {
        'recommend_genre': recommend_genre,
        'reason': reason,
        'recommend_movies_genre': recommend_movies_genre,
        'recommend_movies_score': recommend_movies_score,
        'WEATHER_API_KEY': SECRET_KEY_WEATHER_API_KEY
    }
    return render(request, 'movies/movies_recommend.html', context)


def movie_upcoming(request):
    context = {
        'MOVIE_API_KEY': SECRET_KEY_MOVIE_API_KEY
    }
    return render(request, 'movies/movies_upcoming.html', context)


def review_list(request):
    reviews = MovieReview.objects.order_by('-created_at')

    paginator = Paginator(reviews, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'reviews': reviews,
        'page_obj': page_obj,
    }
    return render(request, 'movies/review_list.html', context)

def review_top_movie(request):

    top_movie_totals = MovieReview.objects.values('movie').annotate(total=Avg('score')).order_by('-total')[:3]

    first_movies = MovieReview.objects.values('movie').annotate(total=Avg('score')).order_by('-total')[0]
    second_movies = MovieReview.objects.values('movie').annotate(total=Avg('score')).order_by('-total')[1]
    last_movies = MovieReview.objects.values('movie').annotate(total=Avg('score')).order_by('-total')[2]
    first_movie = Movie.objects.get(id=first_movies['movie'])
    second_movie = Movie.objects.get(id=second_movies['movie'])
    last_movie = Movie.objects.get(id=last_movies['movie'])

    top_movies = [[first_movie, first_movies['total']], [second_movie, second_movies['total']], [last_movie, last_movies['total']]]

    context = {
        'top_movies': top_movies,
    }
    return render(request, 'movies/review_top_movie.html', context)

def review_list_movie(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    reviews = MovieReview.objects.filter(movie_id=movie.id).order_by('-created_at')
    paginator = Paginator(reviews, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'movie': movie,
        'reviews': reviews,
        'page_obj': page_obj,
    }
    return render(request, 'movies/review_list_movie.html', context)

def review_detail(request, review_id):
    review = get_object_or_404(MovieReview, id=review_id)
    context = {
        'review': review,
    }
    return render(request, 'movies/review_detail.html', context)

@login_required
def review_create(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    if movie.id in request.user.moviereview_set.all().values_list('movie', flat=True):
        review = movie.moviereview_set.get(author=request.user)
        messages.warning(request, '이미 리뷰를 작성한 영화입니다.', extra_tags=review.id)
        return redirect('movies:review_list')
    if request.method == 'POST':
        form = MovieReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.author = request.user
            review.movie = movie
            review.save()
            return redirect('movies:review_list')
    else:
        form = MovieReviewForm()
    context = {
        'form': form,
        'movie': movie,
    }
    return render(request, 'movies/review_create.html', context)


@login_required
def review_create_withoutmovie(request):
    if request.method == 'POST':
        movie = get_object_or_404(Movie, id=request.POST['movie'])
        if movie.id in request.user.moviereview_set.all().values_list('movie', flat=True):
            review = movie.moviereview_set.get(author=request.user)
            messages.warning(request, '이미 리뷰를 작성한 영화입니다.', extra_tags=review.id)
            return redirect('movies:review_list')
        form = MovieReviewWithoutMovieForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.author = request.user
            review.save()
            return redirect('movies:review_list')
    else:
        form = MovieReviewWithoutMovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/review_create.html', context)


def review_update(request, review_id):
    if request.user.is_authenticated:
        review = get_object_or_404(MovieReview, id=review_id)
        if request.user == review.author:
            if request.method == 'POST':
                form = MovieReviewForm(request.POST, instance=review)
                if form.is_valid():
                    review = form.save()
                    return redirect('movies:review_detail', review.id)
            else:
                form = MovieReviewForm(instance=review)
            context = {
                'form': form,
                'review': review,
                'movie': review.movie,
            }
            return render(request, 'movies/review_update.html', context)
        else:
            return redirect('movies:review_detail', review.id)
    else:
        return redirect('accounts:login')


def review_delete(request, review_id):
    if request.user.is_authenticated:
        review = get_object_or_404(MovieReview, id=review_id)
        if request.user == review.author and request.method=='POST':
            movie_id = review.movie.id
            review.delete()
            return redirect('movies:review_list_movie', movie_id)
        else:
            return redirect('movies:review_detail', review.id)
    else:
        return redirect('accounts:login')


def get_movies(request, pageNum, key, genre_key):
    like_movies = list(request.user.like_movies.values_list('id', flat=True))
    exclude_movies = list(request.user.exclude_movies.values_list('id', flat=True))
    later_movies = list(request.user.later_movies.values_list('id', flat=True))
    genre_name = [None, 'Adventure', 'Fantasy', 'Animation', 'Drama', 'Horror', 'Action', 'Comedy', 'Western', 'Thriller', 'Crime', 'Documentary', 'Science Fiction',
                'Mystery', 'Music', 'Romance', 'Family', 'War', 'History', 'TV Movie']

    if genre_key == 0:
        genre_movies = Movie.objects.exclude(id__in=request.user.exclude_movies.all())
    else:
        genre_movies = Genre.objects.get(name=genre_name[genre_key]).movie_set.exclude(id__in=request.user.exclude_movies.all())

    if key == 0:
        movies = list(genre_movies.order_by('-vote_average').values())[pageNum*16:(pageNum+1)*16]
    elif key == 1:
        movies = list(genre_movies.order_by('-release_date').values())[pageNum*16:(pageNum+1)*16]

    max_page = len(genre_movies) // 16
    if len(genre_movies) % 16 == 0:
        max_page -= 1

    return JsonResponse({'movies': movies, 'like_movies': like_movies, 'exclude_movies': exclude_movies, 'later_movies': later_movies, 'max_page': max_page}, status = 200)

def search_movies(request, searchInput, pageNum):

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="/static/movies/index.css">
{% endblock %}


{% block content %}
  <div class="row h-100 align-items-center">
    <div class="mx-auto">
      <h1>지금 바로 {{ movie_count }}개의 영화 정보와<br>{{ review_count }}개의 리뷰를 만나보세요!</h1>
      <div class="text-center my-5">
        {% if request.user.is_authenticated %}
          <a href="{% url 'movies:movie_list' %}"><button class="btn btn-danger">영화 목록으로 이동</button></a>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock %}

movies/templates/movies/review_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'movies/reviewCreate.css' %}">
{% endblock %}


{% block content %}
  {% if request.resolver_match.url_name == 'review_create' %}
  <div class="w-75 mx-auto">
    <h1>'{{ movie }}' 리뷰 작성 중</h1>
    <div class="container">
      <div class="row">
        <div class="col-6">
          <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt="" class="img-thumbnail">
        </div>
        <div class="col-6">
          <h3>{{ movie.title }}</h3>
          <p>{{ movie.overview }}</p>
          <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="float-right btn btn-danger">작성 완료</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% else %}
    <div class="w-50 mx-auto">
      <h1>리뷰 작성</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="float-right btn btn-danger">작성 완료</button>
      </form>
    </div>
  {% endif %}
{% endblock %}

movies/templates/movies/review_detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'movies/reviewDetail.css' %}">
{% endblock %}


{% block content %}
  <div class="container w-75 mx-auto">
    <div class="row">
      <div class="col">
        <img src="https://image.tmdb.org/t/p/original/{{ review.movie.poster_path }}" alt="" class="img-thumbnail">
      </div>
      <div id="app" class="col">
        <h1>{{ review.movie.title }}</h1>
        <p class="overview">{{ review.movie.overview }}</p>
        <hr>
        <h3>한줄평: {{ review.content }}</h3>
        <h3>평점: {{ review.score }}</h3>
        <hr>
        <p>작성자: {{ review.author.nickname }}</p>
        <p>작성일자: {{ review.created_at }}</p>
        <p>수정일자: {{ review.updated_at }}</p>
        {% if request.user == review.author %}
          <div class="d-flex flex-row-reverse bd-highlight">
            <div class="p-2 bd-highlight">
            <form action="{% url 'movies:review_delete' review.id %}" method="POST">
              {% csrf_token %}
              <button class="btn btn-danger">리뷰 삭제</button>
            </form>
            </div>
            <div class="p-2 bd-highlight">
              <a href="{% url 'movies:review_update' review.id %}"><button class="btn btn-danger">리뷰 수정</button></a>
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

movies/templates/movies/review_list.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'movies/reviewList.css' %}">
{% endblock %}


{% block content %}
  {% if messages %}
    {% for message in messages %}
      {% if message.extra_tags %}
        <div class="alert alert-danger" role="alert">{{ message }} 기존 리뷰로 이동하시려면 <a href="{% url 'movies:review_detail' message.extra_tags %}">여기</a>를 클릭해주세요.</div>
      {% endif %}
    {% endfor %}
  {% endif %}

  <h1 class="my-5">리뷰 리스트<a href="{% url 'movies:review_top_movie' %}"><button class="change-button">Top Movie 보기</button></a></h1>
  <table>
    <thead>
      <tr>
        <th>영화 제목</th>
        <th>한줄평</th>
        <th>평점</th>
        <th>작성자</th>
      </tr>
    </thead>
    <tbody>
      {% for review in page_obj %}
        <tr>
          <td><p class="review-title" data-toggle="modal" data-target="#modal-{{review.movie_id}}">{{ review.movie|truncatechars:20 }}</p></td>
          <td>{{ review.content|truncatechars:29 }}</td>
          <td>{{ review.score}}</td>
          <td>{{ review.author }}</td>
          <div class="modal fade" id="modal-{{review.movie_id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{{ review.movie.title }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <img src="https://image.tmdb.org/t/p/original/{{ review.movie.poster_path }}" class="card-img-top" alt="...">
                <div class="modal-body">
                  {{ review.movie.overview }}
                </div>
                <div class="modal-footer">
                  <a href="{% url 'movies:review_list_movie' review.movie.id %}"><button class="btn btn-info">이 영화 리뷰 보러 가기</button></a>
                  <a href="{% url 'movies:review_create' review.movie.id %}"><button class="btn btn-info">이 영화 리뷰 쓰러 가기</button></a>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  
  <a class="review-making-button" href="{% url 'movies:review_create_withoutmovie' %}">리뷰쓰러 가기</a>

  <div class="d-flex justify-content-center">{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true"%}</div>
{% endblock %}

movies/templates/movies/review_list_movie.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'movies/reviewListMovie.css' %}">
{% endblock %}


{% block content %}
  <a href="{% url 'movies:review_create' movie.id %}"><button class="float-right btn btn-outline-light">이 영화 리뷰쓰러 가기</button></a>
  <h1>{{ movie.title }}의 리뷰 리스트</h1>
  {% if not page_obj %}
    <h2>작성된 리뷰가 없습니다.</h2>
  {% else %}
    <table class="table mt-5">
      <thead>
        <tr class="bg-dark text-white">
          <th >한줄평</th>
          <th>평점</th>
          <th>작성자</th>
        </tr>
      </thead>
      <tbody>
        {% for review in page_obj %}
          <tr>
            <td>{{ review.content }}</td>
            <td>{{ review.score }}</td>
            <td>{{ review.author }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}

  <div class="d-flex justify-content-center">{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true"%}</div>
{% endblock %}




{% block vue %}
{% endblock %}

movies/templates/movies/review_top_movie.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'movies/reviewTopMovie.css' %}">
{% endblock %}


{% block content %}
  <h1>사용자 평점 Top 3 Movies<a href="{% url 'movies:review_list' %}"><button class="change-button">전체 리뷰 목록 보기</button></a></h1>

  <div class="top-movies">
    {% for top_movie in top_movies %}
      <img src="https://image.tmdb.org/t/p/original/{{ top_movie.0.poster_path }}" class="w-25" alt="..." data-toggle="modal" data-target="#modal-{{ forloop.counter }}">

      <div class="modal fade" id="modal-{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
          <div class="modal-content">
            <div class="modal-header pb-0">
              <h4>{{ top_movie.0.title }} ({{ top_movie.0.original_title }})</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-8">
                    <img src="https://image.tmdb.org/t/p/original/{{ top_movie.0.backdrop_path }}" class="card-img-top mb-2" alt="...">
                    <p>{{ top_movie.0.overview }}</p>
                  </div>
                  <div class="col-4">
                    <div class="d-flex justify-content-between">
                      <h5 class="d-inline-block my-auto">개봉일 : {{ top_movie.0.release_date }}</h5>
                      <button class='btn btn-outline-success d-inline-block'>{{ top_movie.1 }}</button>
                    </div>
                    <hr class="mb-0">
                    {% for genre in top_movie.0.genres.all %}
                      <button type="button" class="btn btn-outline-secondary mx-2 my-2">{{ genre }}</button>
                    {% endfor %}
                    <hr>
                    <h3> 최근 5개 리뷰</h3>
                    {% for review in top_movie.0.moviereview_set.all|slice:":5" %}
                      <p class="w-100">{{review.author}} - {{review.score}}점</p>
                      <p class="w-100">{{ review.content|truncatechars:23 }}</p>
                    {% endfor %}
                    <hr>
                    <a href="{% url 'movies:review_list_movie' top_movie.0.id %}"><button class="btn btn-outline-info">전체 리뷰 보기</button></a>
                    <a href="{% url 'movies:review_create' top_movie.0.id %}"><button class="btn btn-outline-info">리뷰 작성</button></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

{% endblock %}

movies/templates/movies/review_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'movies/reviewUpdate.css' %}">
{% endblock %}


{% block content %}
  <h1>'{{ movie }}' 리뷰 수정 중</h1>
  <div class="container">
    <div class="row">
      <div class="col">
        <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" alt="" class="img-thumbnail">
      </div>
      <div class="col">
        <h3>{{ movie.title }}</h3>
        <p>{{ movie.overview }}</p>
        <hr>
        <form action="" method="POST">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button class="float-right btn btn-danger">수정 완료</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}