community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.article_index, name='article_index'),
    path('recommend/', views.article_index_recommend, name='article_index_recommend'),
    path('article_create/', views.article_create, name='article_create'),
    path('<int:article_pk>/article_detail/', views.article_detail, name='article_detail'),
    path('<int:article_pk>/article_delete', views.article_delete, name='article_delete'),
    path('<int:article_pk>/article_update', views.article_update, name='article_update'),
    path('<int:article_pk>/article_like/', views.article_like, name='article_like'),
    path('article_search/', views.article_search, name='article_search'),
    path('<int:article_pk>/comment', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('movie_recommend/', views.movie_recommend, name='movie_recommend'),
    path('movie_upcoming/', views.movie_upcoming, name='movie_upcoming'),

    path('review_top_movie/', views.review_top_movie, name='review_top_movie'),
    path('review_list/', views.review_list, name='review_list'),
    path('review_list_movie/<int:movie_id>/', views.review_list_movie, name="review_list_movie"),
    path('review/<int:review_id>/', views.review_detail, name="review_detail"),
    path('review_create_withoutmovie/', views.review_create_withoutmovie, name='review_create_withoutmovie'),
    path('review_create/<int:movie_id>/', views.review_create, name='review_create'),
    path('review_update/<int:review_id>/', views.review_update, name="review_update"),
    path('review_delete/<int:review_id>/', views.review_delete, name="review_delete"),

    path('movie_like/<int:movie_id>/', views.movie_like, name='movie_like'),
    path('movie_exclude/<int:movie_id>/', views.movie_exclude, name='movie_exclude'),
    path('movie_later/<int:movie_id>/', views.movie_later, name='movie_later'),

    path('get_movies/<int:pageNum>/<int:key>/<int:genre_key>/', views.get_movies, name='get_movies'),
    path('search_movies/<str:searchInput>/<int:pageNum>/', views.search_movies, name='search_movies'),

    path('get_genres/<int:movie_id>/', views.get_genres, name='get_genres'),
    path('get_reviews/<int:movie_id>/', views.get_reviews, name='get_reviews'),
    path('make_review/<int:movie_id>/', views.make_review, name='make_review'),
    path('get_movie_recommend/<str:weather>/<str:temp>/', views.get_movie_recommend, name='get_movie_recommend'),

]

community/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 30)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length = 150)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

community/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content']
        exclude = ['like_users', 'author']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.http import JsonResponse
from django.db.models import Q, Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def article_index(request):
    articles = Article.objects.all().order_by('-pk')

    paginator = Paginator(articles, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'articles': articles,
        'page_obj': page_obj
    }
    return render(request, 'community/article_index.html', context)


def article_index_recommend(request):
    articles = Article.objects.annotate(num_like_users=Count('like_users')).order_by('-num_like_users', '-pk')

    paginator = Paginator(articles, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'articles': articles,
        'page_obj': page_obj
    }
    return render(request, 'community/article_index.html', context)


def article_create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ArticleForm(request.POST)
            if form.is_valid():
                article = form.save(commit=False)
                article.author = request.user
                article.save()
            return redirect('community:article_index')
        else:
            form = ArticleForm()
        context = {
            'form': form
        }
        return render(request, 'community/article_create.html', context)
    else:
        return redirect('accounts:login')


def article_detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    form = CommentForm()
    context = {
        'article': article, 'form': form,
    }
    return render(request, 'community/article_detail.html', context)


@require_POST
def article_delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.author:
        article.delete()
        return redirect('community:article_index')
    else:
        return redirect('community:article_detail', article.pk)


def article_update(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if request.user == article.author:
            if request.method == 'POST':
                form = ArticleForm(request.POST, instance=article)
                if form.is_valid():
                    article = form.save()
                    return redirect('community:article_detail', article.pk)
            else:
                form = ArticleForm(instance=article)
            context = {
                'form': form,
                'article': article,
            }
            return render(request, 'community/article_create.html', context)
        else:
            return redirect('community:article_detail', article.pk)
    else:
        return redirect('accounts:login')


def article_like(request, article_pk):
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)
    if article.like_users.filter(pk=user.pk).exists():
        article.like_users.remove(user)
        liked = False
    else:
        article.like_users.add(user)
        liked = True
    return JsonResponse({
        'liked': liked,
        'like_count': article.like_users.count(),
    })


def article_search(request):
    articles = Article.objects.order_by('-pk')
    kw = request.GET.get('kw', '')
    if kw:
        search_result = articles.filter(
            Q(title__icontains=kw)|
            Q(content__icontains=kw)|
            Q(author__username__icontains=kw)
        ).distinct()

        paginator = Paginator(search_result, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'search_result': search_result,
            'kw': kw,
            'page_obj': page_obj
        }
        return render(request, 'community/article_search.html', context)
    else:
        return redirect('community:article_index')


def comment_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.author = request.user
            comment.save()
        return redirect('community:article_detail', article.pk)
    else:
        return redirect('accounts:login')


def comment_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=comment_pk)
        if comment.author == request.user:
            comment.delete()
        return redirect('community:article_detail', article_pk)
    else:
        return redirect('accounts:login')

community/templates/community/article_create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'community/articleCreate.css' %}">
{% endblock %}

{% block content %}
  <div class="w-50 mx-auto">
    <h1>글 작성</h1>
    <form action="", method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% if request.resolver_match.url_name == 'article_create' %}
        <button class="float-right btn btn-danger">글 작성</button>
      {% else %}
        <button class="float-righ btn btn-danger">수정 완료</button>
      {% endif %}
    </form>
  </div>
{% endblock %}

community/templates/community/article_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block css %}
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'community/articleDetail.css' %}">
{% endblock %}

{% block content %}
  <div class="w-75 mx-auto">
    <div class="float-right">
      <p class="my-0">작성일자: {{ article.created_at }}</p>
      <p class="my-0">수정일자: {{ article.updated_at }}</p>
    </div>
    <h1>{{ article.title }}</h1>
    <h5>{{article.author }}</h5>
    <hr>
    <h2>{{ article.content }}</h2>
    <hr>
    <p class="text-white">
      {% if request.user != article.author %}
        {% if user in article.like_users.all %}
          <i data-id="{{ article.pk }}" class="far fa-thumbs-up fa-lg like-button" style="color:red; cursor: pointer;"></i>
        {% else %}
          <i data-id="{{ article.pk }}" class="far fa-thumbs-up fa-lg like-button" style="color:white; cursor: pointer;"></i>
        {% endif %}
      {% else %}
      <div class="float-right">
        <div class="d-flex flex-row-reverse bd-highlight">
          <div class="p-2 bd-highlight">
            <form action="{% url 'community:article_delete' article.pk %}" method='POST'>
              {% csrf_token %}
              <button class="btn btn-danger">글 삭제</button>
            </form>
          </div>
          <div class="p-2 bd-highlight">
            <a href="{% url 'community:article_update' article.pk %}"><button class="btn btn-danger">글 수정</button></a>
          </div>
        </div>
      </div>
      {% endif %}
      <span id="like-count-{{ article.pk }}">추천 {{ article.like_users.all|length }}</span>
    </p>
    <div class="">
      <form action="{% url 'community:comment_create' article.pk %}" method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="float-right btn btn-danger">댓글작성</button>
      </form>
    </div>
    <br>
    <h5 class="text-secondary font-weight-bold mt-5">댓글보기</h5>
    {% for comment in article.comment_set.all %}
      {% if request.user == comment.author %}
        <hr class="comment-div">
        <div class="float-right">
          <form action="{% url 'community:comment_delete' article.pk comment.pk %}" method='POST'>
            {% csrf_token %}
            <button class="btn btn-outline-light float-md-right">삭제하기</button>
          </form>
        </div>
      {% endif %}
      <p class="text-secondary">{{ comment.author }}</p>
      <h5>{{ comment.content }}</h5>
    {% endfor %}
  </div>
{% endblock %}


{% block vue %}
  <script>
    const likeButtons = document.querySelectorAll('.like-button')
    likeButtons.forEach(function(likeButton) {
      likeButton.addEventListener('click', function(event) {
        const articleId = event.target.dataset.id
        axios.get(`/community/${articleId}/article_like/`)
          .then(response => {
            if (response.data.liked) {
              event.target.style.color = 'red'
            } else {
              event.target.style.color = 'white'
            }
            document.querySelector(`#like-count-${articleId}`).innerText = response.data.like_count
          })
          .catch(error => {
            console.log(error)
          })
      })
    })
  </script>
{% endblock %}

community/templates/community/article_index.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'community/articleIndex.css' %}">
{% endblock %}

{% block content %}
  <h1>자유게시판</h1>
  <br>
  <div class="d-flex bd-highlight mb-1">
    <a class="mr-auto p-2 bd-highlight font-weight-bold" href="{% url 'community:article_create' %}"><button class="btn btn-outline-light">글 작성</button></a>
    <div class="dropdown p-2 bd-highlight">
      <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">정렬</button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="{% url 'community:article_index' %}">최신순</a>
        <a class="dropdown-item" href="{% url 'community:article_index_recommend' %}">추천순</a>
      </div>
    </div>
    <form class="form-inline my-2 my-lg-0 bd-highlight" method="GET" action="{% url 'community:article_search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="" aria-label="Search" name="kw" value="{{ kw }}">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">검색</button>
    </form>
  </div>
  <table class="table">
    <thead>
      <tr class="bg-dark text-white">
        <th>번호</th>
        <th>제목</th>
        <th>글쓴이</th>
        <th>등록일</th>
        <th>추천</th>
      </tr>
    </thead>
    {% for article in page_obj %}
      <tbody>
        <tr>
          <td>{{ article.pk }}</td>
          <td><a class="text-white font-weight-bold" href="{% url 'community:article_detail' article.pk %}">{{ article.title }}</a></td>
          <td>{{ article.author }}</td>
          <td>{{ article.created_at|date:"m-d" }}</td>
          <td>{{ article.like_users.all|length }}</td>
        </tr>
      </tbody>
    {% endfor %}
  </table>

  <div class="d-flex justify-content-center">{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true"%}</div>
{% endblock %}

community/templates/community/article_search.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load static %}

{% block css %}
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'community/articleSearch.css' %}">
{% endblock %}

{% block content %}
  <h1>'{{kw}}' 검색 결과</h1>
  {% if not page_obj %}
    <h4>검색 결과가 없습니다.</h4>
  {% else %}
    <h4>총 {{ search_result.all|length }}개의 글이 검색되었습니다.</h4>
  <table class="table">
    <thead>
      <tr class="bg-dark text-white">
        <th>번호</th>
        <th>제목</th>
        <th>글쓴이</th>
        <th>등록일</th>
        <th>추천</th>
      </tr>
    </thead>
    {% for article in page_obj %}
      <tbody>
        <tr>
          <td>{{ article.pk }}</td>
          <td><a class="text-white font-weight-bold" href ="{% url 'community:article_detail' article.pk %}">{{ article.title }}</a></td>
          <td>{{ article.author }}</td>
          <td>{{ article.created_at|date:"m-d" }}</td>
          <td>{{ article.like_users.all|length }}</td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
  {% endif %}

  <div class="d-flex justify-content-center">{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true"%}</div>

{% endblock %}