accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/<int:user_id>/', views.update, name='update'),
    path('detail/<int:user_id>/', views.detail, name='detail'),
    path('get_movies/<int:user_id>/<int:key>/', views.get_movies, name="get_movies"),
    path('get_reviews/<int:user_id>/<int:page>/', views.get_reviews, name="get_reviews"),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.article_index, name='article_index'),
    path('recommend/', views.article_index_recommend, name='article_index_recommend'),
    path('article_create/', views.article_create, name='article_create'),
    path('<int:article_pk>/article_detail/', views.article_detail, name='article_detail'),
    path('<int:article_pk>/article_delete', views.article_delete, name='article_delete'),
    path('<int:article_pk>/article_update', views.article_update, name='article_update'),
    path('<int:article_pk>/article_like/', views.article_like, name='article_like'),
    path('article_search/', views.article_search, name='article_search'),
    path('<int:article_pk>/comment', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    path('', views.movie_list, name='movie_list'),
    path('movie_recommend/', views.movie_recommend, name='movie_recommend'),
    path('movie_upcoming/', views.movie_upcoming, name='movie_upcoming'),

    path('review_top_movie/', views.review_top_movie, name='review_top_movie'),
    path('review_list/', views.review_list, name='review_list'),
    path('review_list_movie/<int:movie_id>/', views.review_list_movie, name="review_list_movie"),
    path('review/<int:review_id>/', views.review_detail, name="review_detail"),
    path('review_create_withoutmovie/', views.review_create_withoutmovie, name='review_create_withoutmovie'),
    path('review_create/<int:movie_id>/', views.review_create, name='review_create'),
    path('review_update/<int:review_id>/', views.review_update, name="review_update"),
    path('review_delete/<int:review_id>/', views.review_delete, name="review_delete"),

    path('movie_like/<int:movie_id>/', views.movie_like, name='movie_like'),
    path('movie_exclude/<int:movie_id>/', views.movie_exclude, name='movie_exclude'),
    path('movie_later/<int:movie_id>/', views.movie_later, name='movie_later'),

    path('get_movies/<int:pageNum>/<int:key>/<int:genre_key>/', views.get_movies, name='get_movies'),
    path('search_movies/<str:searchInput>/<int:pageNum>/', views.search_movies, name='search_movies'),

    path('get_genres/<int:movie_id>/', views.get_genres, name='get_genres'),
    path('get_reviews/<int:movie_id>/', views.get_reviews, name='get_reviews'),
    path('make_review/<int:movie_id>/', views.make_review, name='make_review'),
    path('get_movie_recommend/<str:weather>/<str:temp>/', views.get_movie_recommend, name='get_movie_recommend'),

]

templates/_movie_modal.html
<div class="modal fade" id="modal-{{ movie.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLongTitle">{{ movie.title }} ({{movie.original_title }})</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
      <img src="https://image.tmdb.org/t/p/original/{{ movie.poster_path }}" class="card-img-top" alt="...">
      <div class="modal-body">
      <button class='btn btn-outline-success float-right'>{{ movie.vote_average }}</button>
      <p>개봉일 : {{ movie.release_date }}</p>
      <hr>
      {% if user in movie.like_users.all %}
        <i data-id="{{movie.pk}}" class="fas fa-heart" style="color:red;" data-dismiss="modal">좋아요 취소</i>
      {% else %}
        <i data-id="{{movie.pk}}" class="fas fa-heart" style="color:black;">좋아요</i>
      {% endif %}
      <p><span id="like-count-{{movie.pk}}">{{ movie.like_users.all|length }}</span>명이 좋아합니다!</p>
      <h3>줄거리</h3>
      <p>{{ movie.overview }}</p>
      {% for genre in movie.genres.all %}
        <button type="button" class="btn btn-outline-secondary animated infinite swing delay-1s slow">{{ genre.name }}</button>
      {% endfor %}
      </div>
      <div class="modal-footer">

      {% if user in movie.exclude_users.all %}
        <button data-id="{{movie.pk}}" type="button" class="btn btn-danger exclude-buttons" data-dismiss="modal">실행 취소</button>
      {% else %}
        <button data-id="{{movie.pk}}" type="button" class="btn btn-danger exclude-buttons">안 볼거야!</button>
      {% endif %}

      {% if user in movie.later_users.all %}
        <button data-id="{{movie.pk}}" type="button" class="btn btn-info later-buttons" data-dismiss="modal">안 볼래용</button>
      {% else %}
        <button data-id="{{movie.pk}}" type="button" class="btn btn-info later-buttons">나중에 볼게요//</button>
      {% endif %}
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

templates/_nav.html
<nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="{% url 'index' %}"><h2 class="text-danger font-weight-bold">MovieDay</h2></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">

      {% if request.user.is_authenticated %}
        <div class="btn-group dropdown">
          <button type="button" class="btn btn-secondary">
            <a class="text-decoration-none text-white" href="{% url 'movies:movie_list' %}">
              Movie Card
            </a>
          </button>
          <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'movies:movie_recommend' %}">Movie Recommendation</a>
            <a class="dropdown-item" href="{% url 'movies:movie_upcoming' %}">Upcoming Movie</a>
            <a class="dropdown-item" href="{% url 'movies:review_top_movie' %}">Movie Review</a>
          </div>
        </div>

        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'community:article_index' %}">Community</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'accounts:detail' request.user.id %}">{{ request.user.nickname }}님의 정보</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'accounts:logout' %}">LOGOUT</a>
        </li>
      {% endif %}
      
      {% if request.resolver_match.url_name == 'index' %}
        {% if not request.user.is_authenticated %}
          <a href="{% url 'accounts:login' %}"><button class="btn btn-danger">로그인</button></a>
        {% endif %}
      {% endif %}

    </ul>
  </div>
</nav>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MovieDay</title>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">

  {% block css %}
  {% endblock %}

  <!-- FontAwesom -->
  <script src="https://kit.fontawesome.com/2ecf91688f.js" crossorigin="anonymous"></script>

  <!-- Animate CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"/>
</head>
<body>
  {% include '_nav.html' %}
  
  <div class="container">

    {% block content %}
    {% endblock %}

  </div>

  <!-- Bootstrap -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="{% static 'bootstrap/bootstrap.js' %}"></script>

  <!-- axios -->
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  <!-- vue.js -->
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

  {% block vue %}
  {% endblock %}
  
</body>
</html>